# Application namespace
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    name: app
    environment: lab
---
# Monitoring namespace
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: lab
